### PR TITLE
Update pytest

### PR DESCRIPTION
**Pull request by charleskawczynski**
At the moment, `pytest` does not work out-of-the-box in the root directory (nor in the `test` directory). These changes make `pytest` work out-of-the-box.

### CODE REVIEW

**Comment by charleskawczynski** [comment]
Ah, you're right. I contaminated the directory. I'll update this. The error that I was getting from this was:

```
git clone https://github.com/climate-machine/SCAMPy
Cloning into 'SCAMPy'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 2828 (delta 5), reused 8 (delta 4), pack-reused 2813
Receiving objects: 100% (2828/2828), 5.11 MiB | 4.41 MiB/s, done.
Resolving deltas: 100% (2050/2050), done.

\SCAMPyTest>cd SCAMPy\

\SCAMPyTest\SCAMPy>pytest.exe
================================================= test session starts =================================================
platform win32 -- Python 3.6.5, pytest-4.4.0, py-1.8.0, pluggy-0.9.0
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\Users\\kawcz\\Dropbox\\Caltech\\work\\dev\\SCAMPyTest\\SCAMPy\\.hypothesis\\examples')
rootdir: \SCAMPyTest\SCAMPy
plugins: hypothesis-4.18.3
collected 0 items / 7 errors

======================================================= ERRORS ========================================================
___________________________________ ERROR collecting tests/plots/test_plot_Bomex.py ___________________________________
ImportError while importing test module '\SCAMPyTest\SCAMPy\tests\plots\test_plot_Bomex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\plots\test_plot_Bomex.py:16: in <module>
    import common as cmn
E   ModuleNotFoundError: No module named 'common'
________________________________ ERROR collecting tests/plots/test_plot_DYCOMS_RF01.py ________________________________
ImportError while importing test module '\SCAMPyTest\SCAMPy\tests\plots\test_plot_DYCOMS_RF01.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\plots\test_plot_DYCOMS_RF01.py:16: in <module>
    import common as cmn
E   ModuleNotFoundError: No module named 'common'
_________________________________ ERROR collecting tests/plots/test_plot_GATE_III.py __________________________________
ImportError while importing test module '\SCAMPyTest\SCAMPy\tests\plots\test_plot_GATE_III.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\plots\test_plot_GATE_III.py:17: in <module>
    import common as cmn
E   ModuleNotFoundError: No module named 'common'
...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 7 error in 0.46 seconds ===============================================

```

**Comment by trontrytel** [comment]
OK. I coded it to work as it was described in readme. Does it work for you if you do it this way?

**Comment by charleskawczynski** [comment]
I think it may have. Part of what I was trying to do was allow running the script from any sub-directory of `SCAMPy`, and adding an option for compiling (I hard-coded the compile since I was more interested in refactoring than running)

**Comment by trontrytel** [comment]
@charleskawczynski  can I close this one?

**Comment by charleskawczynski** [comment]
> @charleskawczynski can I close this one?

Yeah, this has gotten a quite stale it looks.

**Pull request closed without merging**
